<?xml version="1.0" encoding="utf-8"?>
<Database Name="TutorMasterDB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Classes">
    <Type Name="Classes">
      <Column Name="ClassCode" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ClassesToFaculty" Member="FacultyClasses" ThisKey="ClassCode" OtherKey="ClassCode" Type="FacultyClasses" DeleteRule="CASCADE" />
      <Association Name="ClassesToStudents" Member="StudentClasses" ThisKey="ClassCode" OtherKey="ClassCode" Type="StudentClasses" DeleteRule="CASCADE" />
      <Association Name="ClassToRequest" Member="TutorRequests" ThisKey="ClassCode" OtherKey="ClassCode" Type="TutorRequests" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="Commitments">
    <Type Name="Commitments">
      <Column Name="CmtID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartTime" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Weekly" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="CmtToStudents" Member="StudentCommitments" ThisKey="CmtID" OtherKey="CmtID" Type="StudentCommitments" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="Faculty">
    <Type Name="Faculty">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="FacultyToClasses" Member="FacultyClasses" ThisKey="ID" OtherKey="FacultyID" Type="FacultyClasses" DeleteRule="NO ACTION" />
      <Association Name="UsersToFaculty" Member="Users" ThisKey="ID" OtherKey="ID" Type="Users" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="FacultyClasses">
    <Type Name="FacultyClasses">
      <Column Name="Key" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FacultyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ClassesToFaculty" Member="Classes" ThisKey="ClassCode" OtherKey="ClassCode" Type="Classes" IsForeignKey="true" />
      <Association Name="FacultyToClasses" Member="Faculty" ThisKey="FacultyID" OtherKey="ID" Type="Faculty" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="StudentClasses">
    <Type Name="StudentClasses">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassCode" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ClassesToStudents" Member="Classes" ThisKey="ClassCode" OtherKey="ClassCode" Type="Classes" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="StudentsToClasses" Member="Students" ThisKey="ID" OtherKey="ID" Type="Students" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="StudentCommitments">
    <Type Name="StudentCommitments">
      <Column Name="CmtID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CmtToStudents" Member="Commitments" ThisKey="CmtID" OtherKey="CmtID" Type="Commitments" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="StudentsToCmt" Member="Students" ThisKey="ID" OtherKey="ID" Type="Students" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Students">
    <Type Name="Students">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tutee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tutor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="StudentsToClasses" Member="StudentClasses" ThisKey="ID" OtherKey="ID" Type="StudentClasses" DeleteRule="CASCADE" />
      <Association Name="StudentsToCmt" Member="StudentCommitments" ThisKey="ID" OtherKey="ID" Type="StudentCommitments" DeleteRule="CASCADE" />
      <Association Name="StudentToRequest" Member="TutorRequests" ThisKey="ID" OtherKey="StudentID" Type="TutorRequests" DeleteRule="CASCADE" />
      <Association Name="UsersToStudents" Member="Users" ThisKey="ID" OtherKey="ID" Type="Users" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="TutorRequests">
    <Type Name="TutorRequests">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassCode" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ClassToRequest" Member="Classes" ThisKey="ClassCode" OtherKey="ClassCode" Type="Classes" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="StudentToRequest" Member="Students" ThisKey="StudentID" OtherKey="ID" Type="Students" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Users">
    <Type Name="Users">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AccountType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="UsersToFaculty" Member="Faculty" ThisKey="ID" OtherKey="ID" Type="Faculty" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="UsersToStudents" Member="Students" ThisKey="ID" OtherKey="ID" Type="Students" Cardinality="One" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>